### ISSUE TITLE
already opened search box overrides the word search

### ISSUE THREAD

**Issue by maximunited** [neilsustc/find-word-at-cursor#3]
Press Ctrl+F, search for 'foo'
scroll through the document, press F3 hoping for search word at cursor, still finds foo

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

This is by design as <kbd>F3</kbd> is by default "find next" in the search mode. This extension aims to do the search without entering the search mode.

![image](https://user-images.githubusercontent.com/7588612/147582642-79768bf5-8f07-4f74-b3ac-f62d6eff43ad.png)
